apiVersion: apps/v1
kind: Deployment
metadata:
  name: kukuk-frontend
  namespace: romeo-prod
spec:
  selector:
    matchLabels:
      app: kukuk-frontend
  template:
    metadata:
      labels:
        app: kukuk-frontend
    spec:
      containers:
        - name: frontend-container
          image: digitalmustermann/kukuk_frontend_prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80   