name: pipeline

on:
  push:
    branches:
      - cicd-mit-jenkins

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin' 
          cache: 'maven'
      
      - name: build 
        run: |
          cd backend
          mvn clean package -Pprod

      - name: Test
        run: |
          cd backend
          mvn test

      - name: Docker build

      - name: Docker push

      - Name: Deploy dev

      - Name: Manual Approval

      - Name: Deploy prod    
